
main_prompt_path: prompts/main_prompt.txt
rag_summarize_prompt_path: prompts/rag_summarize.txt
report_prompt_path: prompts/report_prompt.txt

knowledge_refinement_prompt_path: prompts/knowledge_refinement.txt
